# coding=utf-8
class LoginPageLocator(object):

    email = "//div[@data-reactroot]//div[@class='email-text-label']//input[@type='text']"
    password = "//div[@data-reactroot]//div[@class='password-text-label']//input[@type='password']"
    login_button = "//div[@data-reactroot]//div[@class='login-button']//button[@class='loginEmail']/div"
    expected_user =  "(//div[@class='action-icon-wrapper']//span[@class='username-redesign']/span)[2]"
    fb_email_input = "//input[@id='email']"
    fb_password_input = "//input[@id='pass']"
    fb_login_button = "//input[@name='login']"
    sso_option = "//div[@data-reactroot]//div[@class='non-email-sso vertical-spacing-large']//button[contains(@class, '%s')]/div"
    input_gmail_email =  "//div[@class='Xb9hP']/input[@type='email']"
    input_gmail_password = "//div[@class='Xb9hP']/input[@type='password']"
    button_next_gmail = "//div[@role='button']"
    linkedin_email = "//div[@class='fieldgroup']/input[@type='text']"
    linkedin_password = "//input[@type='password']"
    linkedin_submit = "//input[@type='submit']"
    invalid_email = "//div[@data-reactroot]//div[@class='vertical-spacing-large']//div['@class='password-text-label']//div[@style][text()]"
    forgot_password = "//div[@data-reactroot]//div[@class='login-button']/a[@href]//span[text()='Forgot Password?']"
    email_input_forgot_password = "//div[@class='input-element']//input[@type='email']"
    submit_reset_password = "//div[@class]//button[@type='submit'][text()='GET RESET LINK']"
    new_password = "//div[@class]/div[text()='New Password']/..//div[@class='input-element']/input"
    confirm_password = "//div[@class]/div[text()='Confirm New Password']/..//div[@class='input-element']/input"
    reset_password_button = "//div[@class]//button[@class][text()='RESET']"