# coding=utf-8
class CommonForCardLocator(object):
    """
    Class with common locators
    """

    type_of_card = "//div[@data-reactroot]//div[@class]//span[text()='%s']/../../button/div"
    card_container = "(//div[@data-reactroot]//div[contains(@class, 'card')]//div[@class='paper-card'])[1]"
    insight_menu = "(//div[@class='actions-bar']//div[@class]/div[@class='insight-dropdown']/button/div)[1]"
    menu = "//div[@class='actions-bar']//div[@class]/div[@class='insight-dropdown']/button/div"
    option_inside_menu = "//div[@data-reactroot]//div[contains(@style, '8px 0px; display:')]/div//div[@style]/div[text()='%s']/../../../../span[@class]"
    text_confirm_delete_option = "//div//div/div[@class='vertical-spacing-large']/div/span[text()]"
    confirm_delete = "//div[@class='modal-actions text-right']//button[@class='confirm']"
    message_about_card_deleted = "//*[@id='edc-web-body']/div/div[1]/div/div/span"
    close_rate_content = "//div[@class='close close-button']/button[@type='button']/div"
    action_in_action_bar = "//div[@class='actions-bar']//div[contains(@class, 'icon-inline-block')]/button[@class='%s']"
    num_of_like = "(//div[@data-reactroot]//div[@class='paper-card']//div[@class='actions-bar']//div[contains(@class, 'icon-inline-block')]//small)[1]"
    leave_comment_smartcard = "//div[contains(@id, 'comment')]//input"
    expected_text_comment = "//div[@class='comments-block']//div[@class='comment-list-item']//span[@class='comment-text']/span"
    delete_comment = "(//div[@data-reactroot]//div/span[contains(@class, 'delete')])[1]"
    text_confirm_delete = "//div[@class='container-padding']//div[@class='vertical-spacing-large']//span"
    cross_close = "//div[@class='card-overview-header']//div[@class='close close-button']/button[@type='button']"
    arrow_go_back = "//div[@class='breadcrumbBack']/a[@class]"
    text_about_completed_card = "//*[@id='edc-web-body']/div/div[1]/div/div/span"
    statistic_table_row_1 = "(//div[@class='cardStats']//div[contains(@class, '%s')]//tbody//div/div)[1]"
    statistic_table_row_2 = "(//div[@class='cardStats']//div[contains(@class, '%s')]//tbody//div/div)[2]"
    close_card_statistic = "//div[@data-reactroot]//div[@class='cardStats']//span"
    message_text = "(//div[@data-reactroot]//div[@style]//div[@style]/span)[1]"
    last_pathway = "(//div[@data-reactroot]//div[@style]//table//tbody//tr//td//div//label/a[@class][text()]/../..//*[@viewBox])[last()-1]"
    add_to_pathway = "//div[@data-reactroot]//div//div[@class]//button[@class='create']"
    post_to_channel_specific_name = "//div[@style]//div[@class='container-padding']//table//tbody//tr//div[@class]//span[@class][text()='%s']/../../../input"
    post_to_channel_button = "//div[@class='text-center']//button[@class='create']"
    message_content_posted = "//div[@class]/div//div[@class='StatusModal']/p/span"
    group_name_in_channel = "//div[@data-reactroot]//div[@class='row discovery-contents']//div[@class='channel-course']//div[@class='title channel'][text()='%s']/../../../div"
    level_complexity_on_card = "//div[@class='level']"
    level_complexity_inside_card = "//div[@class='level']//div[@id]//div[@style]/div[text()]"
    tag_input_field = "//div[@class='react-tags']//input[contains(@placeholder, 'Add Tags')]"
    tags_on_card = "(//div[@class='topics-list'])[1]"
    assign_window = "(//div[@data-reactroot]//div[@class='groups-assign-modal'])[1]"
    create_assign = "//div[@class='text-right']//button[@class='create']"
    confirm_assign = "//div[@class='text-right']//button[@class='confirm']"
    message_about_assign = "//div[@style]/span[text()='Assigned to you.']"
    data_button = "(//div[@style]/label/../div[contains(@style, 'transition')]//div[contains(@style, 'color')])[2]"
    input_data = "//input[contains(@id, 'SelectaDate')]"
    number_of_assignment = "//div[contains(@class, 'myAssignments')]//span/div"
